[package]
name = "screen_key_rec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
device_query = "1.1.3"
screenshots = "0.5.3"
